/*
    Here all the queries use 'SELECT' clause to display the result table.
*/
USE sql10am;    -- to use the sql10am database

-- 1. NAME AND COMM OF EMP
SELECT ENAME,COMM
FROM EMP;

-- 2. EMPID AND DEPTNO FROM EMP
SELECT EMPNO, DEPTNO
FROM EMP;

-- 3. EMPNAME AND HIREDATE FROM EMP
SELECT ENAME, HIREDATE
FROM EMP;

-- 4. NAME AND DESIGNATION FROM EMP
SELECT ENAME, JOB
FROM EMP;

-- 5. NAME,JOB,SAL FROM EMP
SELECT ENAME, JOB, SAL 
FROM EMP;

-- 6. NAME AND SAL FROM EMP
SELECT ENAME, SAL
FROM EMP;

-- 7. DEPTNAME AND LOC PRESENT IN DEPT TABLE
SELECT DNAME,LOC 
FROM DEPT;

-- 8. DEPTNAME PESENT IN DEPT TABLE
SELECT DNAME
FROM DEPT;

-- 9. DEPTNO OF EMPLOYEES
SELECT DISTINCT DEPTNO 
FROM EMP;

-- 10. DEPTNO OF EMPLOYEES IN DEPT TABLE
SELECT DEPTNO
FROM DEPT;

-- 11. NAME OF EMP
SELECT ENAME
FROM EMP;

-- 12. NAME,SAL OF EMP
SELECT ENAME, SAL
FROM EMP;

-- 13. NAME, EMPNO AND SAL OF EMPS
SELECT ENAME, EMPNO , SAL
FROM EMP;

-- 14. NAME, SAL, HIREDATE AND COMM OF EMP
SELECT ENAME, SAL, HIREDATE, COMM
FROM EMP;

-- 15. DETAILS OF EMP
SELECT *
FROM EMP;

-- 16. ANNUAL SAL OF EMP
SELECT SAL*12 
FROM EMP;

-- 17. HALF TERM SAL OF EMP
SELECT SAL*6
FROM EMP;

-- 18. ANNUAL SAL AND 6 MONTH COMM
SELECT SAL*12 , COMM * 6
FROM EMP;

-- 19. HALF TERM SAL OF EMP AND RS. 5000 INCREMENT IN THEIR ANNUAL SAL
SELECT SAL*6, SAL*12 + 5000
FROM EMP;

-- 20. NAME, SAL OF EMP WITH ANNUAL COMM, 2000 INCREMENT IN HALF TERM COMM, 5000 DECREMENT IN ANNUAL SAL
SELECT ENAME, SAL, COMM*12, COMM*6 + 2000, SAL*12- 5000
FROM EMP;

-- 21. DETAILS OF EMP, ALONG WITH ANNUAL SAL
-- HERE, we have to mention TABLE_NAME before asterisk, eg. EMP.*
SELECT EMP.*, SAL*12
FROM EMP;

-- 22. NAME OF EMP WITH ALTERNATE NAME AS EN
SELECT ENAME AS EN
FROM EMP;

-- 23. DEPT NO OF EMPS WITHOUT REPITATION
SELECT DISTINCT DEPTNO
FROM EMP;SELECT EMPNO, DEPTNO FROM EMP LIMIT 0, 2000;
