USE SQL10AM;
-- 01 ANNUAL SAL OF EMPS WHOSE NAME IS SMITH
SELECT SAL*12 
FROM EMP
WHERE ENAME = 'SMITH';

-- 02 NAME OF EMPS WORKING AS CLERK
SELECT ENAME
FROM EMP
WHERE JOB= 'CLERK';

-- 03 SAL OF EMPS WORKING AS SALESMAN
SELECT SAL
FROM EMP
WHERE JOB = 'SALESMAN';

-- 04 DEATILS OF EMPS WITH SAL MORE THAN 2000
SELECT  *
FROM EMP
WHERE SAL >2000;

-- 05 DETAILS OF EMPS WHOSE NAME IS JONES
SELECT *
FROM EMP
WHERE ENAME = 'JONES';

-- 06 DETAILS OF EMPS HIRED AFTER 01 JAN 1981
SELECT *
FROM EMP
WHERE HIREDATE > '1981-01-01';

-- 07 NAME AND SAL WITH ANNUAL SAL WHOSE SAL > 10200
SELECT ENAME, SAL, SAL*12 
FROM EMP
WHERE SAL > 10200;

-- 08 DISPLAY EMPNO OF EMPS WORKING IN DEPTNO 30
SELECT EMPNO
FROM EMP
WHERE DEPTNO = 30;

-- 09 DISPLAY NAME, HIREDATE IF HIRED AFTER 1981
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE >= '1982-01-01';

-- 10 DISPLAY DETAIL OF EMPS WORKING AS MANAGER
SELECT *
FROM EMP
WHERE JOB= 'MANAGER';

-- 11 DISPLAY NAME AND SAL OF EMP EARNING COMMISION 1400
SELECT ENAME, SAL
FROM EMP
WHERE COMM = 1400;

-- 12 DISPLAY DETAIL OF EMPS WITH SAL MORE THAN 2000
SELECT *
FROM EMP
WHERE SAL >2000;

-- 13 DETAILS OF EMP, WITH ANNUAL SAL WHERE HIREDATE MORE THAN 2000
SELECT EMP.*, SAL*12 ANNUAL_SAL
FROM EMP
WHERE HIREDATE >= '2001-01-01';

-- 14 NAME , SAL FROM EMP WHERE SAL MORE THAN 5000
SELECT ENAME, SAL
FROM EMP
WHERE SAL>5000;

-- 15 NAME, COMM OF EMP WHERE EMPS WORKING AS SALESMAN
SELECT ENAME, COMM
FROM EMP
WHERE JOB= 'SALESMAN';