-- SUBQUERY 
-- ==========================================
-- 01 DETAILS OF EMP HIRED AFTER SMITH AND BEFORE SCOTT
SELECT *
FROM EMP
WHERE HIREDATE > (SELECT HIREDATE FROM EMP
					WHERE ENAME = 'SMITH') 
	AND 
		HIREDATE < (SELECT HIREDATE FROM EMP
						WHERE ENAME = 'SCOTT');

-- 02 WAQ TO DISPLAY DNAME OF RAJ
SELECT DNAME
FROM DEPT 
WHERE DEPTNO = (SELECT DEPTNO FROM EMP
					WHERE ENAME = 'SCOTT');
                    
-- 03 DETAILS OF EMP EARNING MORE THAN ALLEN BUT LESS THAN SCOTT
SELECT *
FROM EMP
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'ALLEN') 
		AND SAL < (SELECT SAL FROM EMP WHERE ENAME = 'SCOTT');
        
-- 04 DISPLAY NAME FROM EMP EARNING 2ND MAX SAL
SELECT ENAME
FROM EMP
WHERE SAL = (SELECT DISTINCT SAL FROM EMP
				ORDER BY SAL DESC
				LIMIT 1 OFFSET 1);
-- OR
SELECT ENAME, SAL
FROM (
    SELECT ENAME, SAL, 
           DENSE_RANK() OVER (ORDER BY SAL DESC) as SalaryRank
    FROM EMP
) AS RankedSalaries
WHERE SalaryRank = 2;

-- 03 LOC OF AN EMP EARNING 3RD MIN SAL
SELECT LOC
FROM DEPT 
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP 
					WHERE SAL = (
							SELECT DISTINCT SAL
                            FROM EMP
                            ORDER BY SAL 
                            LIMIT 1 OFFSET 2
                    ));
-- OR

WITH RankedSalaries AS (
    SELECT e.DEPTNO, 
           DENSE_RANK() OVER (ORDER BY SAL ASC) as SalRank
    FROM EMP e
)
SELECT d.LOC
FROM DEPT d
JOIN RankedSalaries rs ON d.DEPTNO = rs.DEPTNO
WHERE rs.SalRank = 3;

-- WAQTD DETAILS OF EMP WORKING AS PRESIDENT AND SAL MORE THAN SCOTT AND HIRED AFTER SMITH
SELECT *
FROM EMP
WHERE JOB = 'PRESIDENT' 
	AND SAL > (SELECT SAL FROM EMP WHERE ENAME = 'SCOTT') 
    AND HIREDATE > (SELECT HIREDATE FROM EMP WHERE ENAME = 'SMITH');
    
/*
	WAQOTD DETAILS OF EMP AND DEPT TABLE IF EMP IS HIRED BEFORE ADAMS AND AFTER ALLEN, EMP SHOULD NOT EARN
	ANY COMM AND HAVE CHAR 'A' IN NAME BUT LOC SHOULD NOT HAVE CHAR 'P' AND EMP SHOULD EARN MORE THAN WARD'S MANAGER
*/
SELECT e.*, d.*
FROM EMP e
JOIN DEPT d ON e.DEPTNO = d.DEPTNO
JOIN EMP adams ON adams.ENAME = 'ADAMS'
JOIN EMP allen ON allen.ENAME = 'ALLEN'
JOIN EMP ward ON ward.ENAME = 'WARD'
JOIN EMP ward_mgr ON ward.MGR = ward_mgr.EMPNO
WHERE e.HIREDATE < adams.HIREDATE        -- Before Adams
  AND e.HIREDATE > allen.HIREDATE        -- After Allen
  AND (e.COMM IS NULL OR e.COMM = 0)     -- No Commission
  AND e.ENAME LIKE '%A%'                 -- 'A' in name
  AND d.LOC NOT LIKE '%P%'               -- No 'P' in Location
  AND e.SAL > ward_mgr.SAL;              -- More than Ward's Manager
