-- SUBQUERY 
-- ==========================================
-- 01 DETAILS OF EMP HIRED AFTER SMITH AND BEFORE SCOTT
SELECT *
FROM EMP
WHERE HIREDATE > (SELECT HIREDATE FROM EMP
					WHERE ENAME = 'SMITH') 
	AND 
		HIREDATE < (SELECT HIREDATE FROM EMP
						WHERE ENAME = 'SCOTT');