USE SQL10AM;

-- CONCATINATION OPERATOR
SELECT CONCAT('Hey! ',ENAME,' your salary is ',SAL,' and you get Rs. 3000 hike, so you will get ', SAL + 3000) AS new_sal
FROM EMP;

-- IN OPERATOR
-- ============================
-- 01 NAME AND COMM FROM EMP WHERE HIREDATE IN '1981-03-12' OR '1981-09-28'
SELECT ENAME,COALESCE(COMM,0)
FROM EMP
WHERE HIREDATE IN ('1981-03-12','1981-09-28');

-- BETWEEN OPERATOR
-- ==========================
-- 1. DETAILS OF EMP HIRED IN THE YEAR 1981
SELECT *
FROM EMP
WHERE HIREDATE BETWEEN '1981-01-01' AND '1981-12-31';

-- ALL COMBINED
/*
	DETAILS OF EMP WORKING IN DEPTNO 30,10,20 EXCEPT PRESIDENT AND ANALYST AND HIRED AFTER 1980 BUT BEFORE 85 EXCEPT THE EMPLOYEE HIRED ON 3RD DEC 81 
	AND 20 FEB 81 ALONG WITH YEAR 82 AND THE NAME SHOULD HAVE CHARACTER A AND THE PERSON SHOULD EARN 4 DIGIT SAL AND SHOULD NOT HAVE CHAR P IN THE DESIGNATION
	AND SHOULD NOT EARN ANY COMM BUT SHOOULD HAVE MGR
*/
SELECT * 
FROM EMP
WHERE DEPTNO IN (30,10,20) AND JOB NOT IN ('PRESIDENT','ANALYST') 
		AND HIREDATE >= '1981-01-01' AND HIREDATE < '1985-01-01' 
        AND HIREDATE NOT IN ('1981-12-03','1981-02-20') 
        AND HIREDATE NOT BETWEEN '1982-01-01' AND '1982-12-31' 
        AND ENAME LIKE 'A%'
        AND SAL LIKE '____'
        AND JOB NOT LIKE '%P%'
        AND COMM IS NULL 
        AND MGR IS NOT NULL;
 
 -- creating a function
DELIMITER //

CREATE FUNCTION GetAnnualIncome (sal DECIMAL(10,2), comm DECIMAL(10,2))
RETURNS DECIMAL(10,2)
DETERMINISTIC
BEGIN
    RETURN (sal + COALESCE(comm, 0)) * 12;
END //

DELIMITER ;